### ISSUE TITLE
Error spam when parrying* in a server

### ISSUE THREAD

**Issue by boniblade** [bglandolt/bettercombat#28]
My server host is Aternos, Forge 1.12.2.
I initially thought this problem was caused by Toroquest, but after uninstalling it, I still receive this error spam until my server crashes. (lost connection: A fatal error has occurred, this connection is terminated)
I assume this is the cause, atleast:
.
.
.
<html>
<body>

[22:56:55] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
--
11458 | io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type bettercombat.mod.network.PacketParried in channel bettercombat
11459 | at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
11460 | at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
11461 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
11462 | at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
11463 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
11464 | at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
11465 | at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
11466 | at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
11467 | at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
11468 | at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
11469 | at bettercombat.mod.handler.EventHandlers.livingAttackEvent(EventHandlers.java:661) [EventHandlers.class:1.0]
11470 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_925_EventHandlers_livingAttackEvent_LivingAttackEvent.invoke(.dynamic) [?:?]
11471 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
11472 | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
11473 | at net.minecraftforge.common.ForgeHooks.onPlayerAttack(ForgeHooks.java:591) [ForgeHooks.class:14.23.5.2860]
11474 | at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:994) [aed.class:?]
11475 | at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) [oq.class:?]
11476 | at net.torocraft.toroquest.entities.EntitySentry.attackTargetEntityWithCurrentItem(EntitySentry.java:2917) [EntitySentry.class:?]
11477 | at net.torocraft.toroquest.entities.EntitySentry.func_70652_k(EntitySentry.java:2835) [EntitySentry.class:?]
11478 | at net.torocraft.toroquest.entities.AIAttackWithSword.checkAndPerformAttack(AIAttackWithSword.java:233) [AIAttackWithSword.class:?]
11479 | at net.torocraft.toroquest.entities.AIAttackWithSword.func_75246_d(AIAttackWithSword.java:151) [AIAttackWithSword.class:?]
11480 | at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
11481 | at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?]
11482 | at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) [vp.class:?]
11483 | at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
11484 | at net.torocraft.toroquest.entities.EntityToroMob.func_70636_d(EntityToroMob.java:95) [EntityToroMob.class:?]
11485 | at net.torocraft.toroquest.entities.EntitySentry.func_70636_d(EntitySentry.java:1068) [EntitySentry.class:?]
11486 | at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) [vp.class:?]
11487 | at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [vq.class:?]
11488 | at net.minecraft.world.World.func_72866_a(World.java:1996) [amu.class:?]
11489 | at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
11490 | at net.minecraft.world.World.func_72870_g(World.java:1958) [amu.class:?]
11491 | at net.minecraft.world.World.func_72939_s(World.java:1762) [amu.class:?]
11492 | at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
11493 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
11494 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
11495 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
11496 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
11497 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
11498 | Caused by: java.lang.RuntimeException: Undefined discriminator for message type bettercombat.mod.network.PacketParried in channel bettercombat
11499 | at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexedMessageToMessageCodec.class:?]
11500 | at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
11501 | at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
11502 | ... 38 more

</body>
</html>

**Comment by boniblade** [comment]
Here is another log of the same error that gets spammed everytime I parry. This is without Toroquest; so it must be part of BetterCombat instead.

<html>
<body>

[23:15:50] [Netty Epoll Server IO #2/ERROR] [FML]: There was a critical exception handling a packet on channel bettercombat
--
2924 | io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type bettercombat.mod.network.PacketParried in channel bettercombat
2925 | at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
2926 | at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
2927 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
2928 | at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
2929 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
2930 | at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
2931 | at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
2932 | at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
2933 | at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
2934 | at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) ~[SimpleNetworkWrapper.class:?]
2935 | at bettercombat.mod.handler.EventHandlers.livingAttackEvent(EventHandlers.java:661) ~[EventHandlers.class:1.0]
2936 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_889_EventHandlers_livingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
2937 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
2938 | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
2939 | at net.minecraftforge.common.ForgeHooks.onPlayerAttack(ForgeHooks.java:591) ~[ForgeHooks.class:14.23.5.2860]
2940 | at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:994) ~[aed.class:?]
2941 | at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) ~[oq.class:?]
2942 | at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99) ~[ade.class:?]
2943 | at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178) ~[xo.class:?]
2944 | at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167) ~[xo.class:?]
2945 | at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
2946 | at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
2947 | at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) ~[vp.class:?]
2948 | at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
2949 | at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45) ~[ade.class:?]
2950 | at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
2951 | at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
2952 | at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50) ~[ade.class:?]
2953 | at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
2954 | at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
2955 | at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
2956 | at net.minecraft.world.World.func_72939_s(World.java:1762) ~[amu.class:?]
2957 | at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
2958 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
2959 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
2960 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
2961 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
2962 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
2963 | Caused by: java.lang.RuntimeException: Undefined discriminator for message type bettercombat.mod.network.PacketParried in channel bettercombat
2964 | at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexedMessageToMessageCodec.class:?]
2965 | at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
2966 | at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
2967 | ... 37 more
2968 | [23:15:50] [Netty Epoll Server IO #2/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated


</body>
</html>[23:15:50] [Netty Epoll Server IO #2/ERROR] [FML]: There was a critical exception handling a packet on channel bettercombat
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type bettercombat.mod.network.PacketParried in channel bettercombat
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) ~[SimpleNetworkWrapper.class:?]
	at bettercombat.mod.handler.EventHandlers.livingAttackEvent(EventHandlers.java:661) ~[EventHandlers.class:1.0]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_889_EventHandlers_livingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlayerAttack(ForgeHooks.java:591) ~[ForgeHooks.class:14.23.5.2860]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:994) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) ~[oq.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99) ~[ade.class:?]
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178) ~[xo.class:?]
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167) ~[xo.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45) ~[ade.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50) ~[ade.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.func_7[2939](https://aternos.org/log/#L2939)_s(World.java:1762) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type bettercombat.mod.network.PacketParried in channel bettercombat
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
	... 37 more
[23:15:50] [Netty Epoll Server IO #2/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated

**Comment by bglandolt** [comment]
fixed
